'use client';

import { getDesignTokens } from './configs/theme';
import './globals.css';

//MUI
import { ThemeProvider, createTheme } from '@mui/material';
import store from './store/store';
import { Provider } from 'react-redux';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
    const themeConfig = createTheme(getDesignTokens('light'));

    return (
        <html lang='en'>
            <body>
                <Provider store={store}>
                    <ThemeProvider theme={themeConfig}>{children}</ThemeProvider>
                </Provider>
            </body>
        </html>
    );
}
