import { useLocale } from 'next-intl';
import { notFound } from 'next/navigation';

//Assets
import './../globals.css';

//Components
import AppLayout from './components/layout/app-layout';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children, params }) {
    const locale = useLocale();

    if (params.locale !== locale) {
        notFound();
    }

    return (
        <html lang={locale}>
            <body>
                <AppLayout>{children}</AppLayout>
            </body>
        </html>
    );
}
