import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import Cookies from 'js-cookie';

// Assets
import '../globals.css';

// Components
import AppLayout from './components/layout/app-layout';

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export function generateStaticParams() {
   return [{ locale: 'en' }, { locale: 'fa' }];
}

export default async function RootLayout({ children }) {
   const locale = Cookies.get('neuroCodeLocale') || 'en';

   let messages = null;
   try {
      messages = (await import(`../../messages/${locale}.json`)).default;
   } catch (error) {
      notFound();
   }

   return (
      <html lang={locale}>
         <body>
            <NextIntlClientProvider locale={locale} messages={messages}>
               <AppLayout currentLocale={locale}>{children}</AppLayout>
            </NextIntlClientProvider>
         </body>
      </html>
   );
}
